version: '3.8'

services:
  anki_connect:
    image: "thisisnttheway/headless-anki:main"
    container_name: wotd_anki-connect
    ports:
      - "5900:5900"
      - "8765:8765"
    volumes:
      - myapp:/data
    networks:
      - app_network



  db:
    image: postgres:alpine3.19
    container_name: wotd_db
    ports: 
      - 5432:5432
    volumes:
      - ./wotd-db/volume:/var/lib/postgresql/data
      - ./wotd-db/scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - ./wotd-db/config/.env

  # backend:
  #   image: "dermacon/checklist-paste-bin_backend:1.0"
  #   build: ./backend/
  #   ports:
  #     - "8081:5000"
  #   volumes:
  #     - ./tmp-checklist/:/app/tmp/
  # frontend:
  #   depends_on:
  #       - backend
  #   image: "dermacon/checklist-paste-bin_frontend:1.0"
  #   build: ./frontend/
  #   ports:
  #     - "8080:80"

networks:
  app_network:
    driver: bridge

volumes:
  myapp:

