version: '3.8'

services:
  anki_connect:
    image: "thisisnttheway/headless-anki:main"
    container_name: wotd_anki-connect
    ports:
      - "5900:5900"
      - "8765:8765"
    volumes:
      - myapp:/data
    networks:
      - app_network

  db:
    image: postgres:alpine3.19
    container_name: wotd_db
    ports: 
      - 5432:5432
    volumes:
      - ./wotd-db/volume:/var/lib/postgresql/data
      - ./wotd-db/scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - ./wotd-db/config/.env

  backend:
    depends_on:
      - db
      - anki_connect
    image: "dermacon/wotd_backend:1.0"
    container_name: wotd_backend
    build: ./wotd-backend/
    env_file: .env
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - ANKI_CONNECT_HOST=anki_connect
      - ANKI_CONNECT_DATA_PORT=8765
      - ANKI_CONNECT_LOGIN_PORT=5900
    ports:
      - "5000:5000"
    volumes:
      - ./logs/wotd_backend/:/app/tmp/logs/

  # frontend:
  #   depends_on:
  #       - backend
  #   image: "dermacon/checklist-paste-bin_frontend:1.0"
  #   build: ./frontend/
  #   ports:
  #     - "8080:80"

networks:
  app_network:
    driver: bridge

volumes:
  myapp:

